---
- hosts: all
  become: true

  vars_files:
    vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php-mysql
    - geerlingguy.php

  tasks:
    - import_tasks: tasks/main.yml
