---
- hosts: cluster
  become: yes

  vars:
    list_of_packages: 
      - ntp
      - vim
      - nano
      - sshpass
      - unzip
      - python3-apt
      - dnsutils
      - dos2unix
      - whois
      - curl
      - lynx
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - docker-ce 
      - docker-ce-cli 
      - containerd.io

  tasks:
    - name: Add master IP to known_hosts file
      known_hosts:
        path: /home/vagrant/.ssh/ssh_known_hosts
        name: "{{ master_hostname }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa {{ master_hostname }}') }}"

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker and and other dependencies
      package:
        name: "{{ list_of_packages }}"
        state: present
      notify:
        - restart docker

    - name: Remove default containerd file
      file:
        path: /etc/containerd/config.toml
        state: absent
      notify:
        - restart containerd

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        group: docker
      notify:
        - restart docker
    
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      loop:
        - swap
        - none

    - name: Disable swap
      shell: swapoff -a
      when: ansible_swaptotal_mb > 0
      
    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      package: 
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - kubelet 
          - kubeadm 
          - kubectl

    - name: Reset Kubernetes cluster
      shell: kubeadm reset -f

    - name: Remove CNI configuration
      file:
        path: /etc/cni/net.d/10-flannel.conflist
        state: absent

    - name: Remove kube config file
      file:
        path: /home/vagrant/.kube/config
        state: absent

    - name: Reset iptables
      shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

  handlers:
    - name: restart docker
      service: name=docker state=restarted

    - name: restart containerd
      service: name=containerd state=restarted
