apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: aisi
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.6
        ports:
          - containerPort: 27017
        volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
      - name: mongo-data
        hostPath:
          path: /mnt/data/mongo
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: aisi
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
